### ISSUE TITLE
Align the whole file

### ISSUE THREAD

**Issue by rolyataylor2** [chemoish/atom-valign#15]
I was wondering if there was a way to auto-format an entire file with Valign instead of having to place my cursor on the segment to be aligned?

**Comment by chemoish** [comment]
Unfortunately, there is not. This package's goal was intended to format as needed—incase you did not want some part formatted.

I would think that would be done by a beautifier instead.

Also, this package includes very little grammar (so it works on files with undefined grammar—minus JS because the stupid `var` keyword [which still has bugs]).

…But that makes it break on anything grammar specific.

```js
{
  'key => value': true
}
```

In every case dealing with strings it will find the first match and not align as intended.

If you have any recommendations on how to achieve this without grammar (or little grammar), let me know.

**Comment by rolyataylor2** [comment]
Darn I had a plugin I had written for Brackets that would parse a whole file and align end of line comments as well as operators; It wouldn't align the var statements though... But since I switched to atom I deleted it. Thanks for the reply though. I will have to figure out coffee scripting eventually.
