### ISSUE TITLE
Alignment replaces indentation with spaces

### ISSUE THREAD

**Issue by ShimShamSam** [chemoish/atom-valign#3]
Whenever I trigger an alignment, my tab indentations are replaced with spaces. This makes the plugin too destructive for me to use. Why is it even touching my indentation in the first place?

**Comment by chemoish** [comment]
Fixed https://github.com/chemoish/atom-valign/commit/ffd80e184c36108181c1713d13768eaf5b1de93a

**Comment by chemoish** [comment]
Sorry for the extremely late update.

The code does not use the Grammar API for one thing… but each line is made up of multiple parts. Indentation, keywords, operators, etc. and…

It is touching the indentation because entire lines are replaced during the formatting process. This was the easiest way of doing it (at the time of writing), rather than inserting spaces/formatting at specific editor coordinates.
